# SPDX-FileCopyrightText: Copyright (c) 2023 - 2025 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Model name
model_name: 'regression' # 'regression', 'diffusion', or custom model added by user

# Model conditions
regression_conditions: ["state", "background", "invariant"] # list consisting of "state", "background", "invariant" (default from StormCast paper)
diffusion_conditions: ["state", "regression", "invariant"] # list consisting of "state", "regression", "background", "invariant" (default from StormCast paper)

# Model hyperparameters
spatial_pos_embed: False # Whether or not to add an additive position embed after the first conv in the U-Net
model_type: "SongUNetPosEmbd" # Model class to use
# Example overrides for architecture hyperparameters (uncomment to customize)
# hyperparameters:
#   channel_mult: [1, 2, 2]
#   num_blocks: 2
#   model_channels: 128
#   attn_resolutions: [] # Internal resolutions within the U-Net to apply self-attention
#   bottleneck_attention: false
#   checkpoint_level: 0

# Pretrained regression model
regression_weights: "stormcast_checkpoints/regression/UNet.0.0.mdlus" # Path to pretrained regression network,
                                                                      # used if 'regression' is included in diffusion_conditions
